package ecosystem_test

import (
	. "github.com/onsi/ginkgo/v2"
	"github.com/openshift-pipelines/release-tests-ginkgo/pkg/oc"
)

// ecosystem_patterns_test.go -- Reference implementation of the DescribeTable/Entry
// pattern used throughout the ecosystem test suite.
//
// This file lives in the same package (ecosystem_test) as suite_test.go and therefore
// has access to the shared variable `sharedClients` initialised in BeforeSuite.
//
// The DescribeTable pattern is the primary migration vehicle for Phase 4, where 36+
// ecosystem task tests follow the same flow with different parameters.

var _ = Describe("DescribeTable Pattern", func() {

	// DescribeTable generates a separate It block (and thus a separate JUnit XML
	// <testcase>) for every Entry row.  This is critical for Polarion test-case
	// mapping: each pipeline/task variant gets its own pass/fail verdict.
	DescribeTable("Ecosystem Task Validation",
		func(taskName, yamlPath, expectedStatus string) {
			// Skip until actual test fixtures and cluster access are available.
			// Remove this Skip when migrating real tests in Phase 4.
			Skip("pattern demonstration -- requires cluster and test fixtures")

			// --- Namespace lifecycle ------------------------------------------------
			// Create a unique namespace per table entry so tests are fully isolated.
			ns := "ecosystem-" + taskName
			oc.CreateNewProject(ns)
			DeferCleanup(oc.DeleteProjectIgnoreErrors, ns)

			// --- Apply test fixture -------------------------------------------------
			// yamlPath is relative to the config.Dir() template directory.
			oc.Create(yamlPath, ns)

			// --- Poll for expected completion status --------------------------------
			// In real tests this would use Eventually + a status-checking helper:
			//
			//   Eventually(func() string {
			//       return getPipelineRunStatus(sharedClients, ns, taskName)
			//   }, config.APITimeout, config.APIRetry).Should(Equal(expectedStatus))
			//
			// sharedClients (from suite_test.go BeforeSuite) provides the typed
			// Kubernetes client set for API calls.
			_ = expectedStatus // placeholder until real assertion is added
		},

		// Labels applied to every Entry generated by this DescribeTable.
		Label("ecosystem", "e2e"),

		// -----------------------------------------------------------------------
		// CRITICAL: Entry parameters are evaluated at TREE CONSTRUCTION TIME,
		// not at test execution time.
		//
		//   - Only use string/int/bool literals, package-level constants, or pure
		//     functions whose return value does not depend on test-time state.
		//
		//   - NEVER pass variables that are initialised in BeforeEach/BeforeSuite
		//     as Entry parameters.  Those variables are zero-valued when the spec
		//     tree is built and will cause confusing failures.
		//
		//   - Dynamic data (e.g. generated namespace names, client handles) must
		//     be accessed INSIDE the table body function, not passed through Entry.
		//
		//   - Each Entry generates a separate spec with its own description string.
		//     The first argument to Entry becomes the spec name in JUnit XML output,
		//     which Polarion uses for test-case identification.
		// -----------------------------------------------------------------------

		Entry("buildah pipeline: PIPELINES-XX-TC01",
			"buildah", "ecosystem/buildah-pipeline.yaml", "Succeeded"),

		Entry("s2i-java pipeline: PIPELINES-XX-TC02",
			"s2i-java", "ecosystem/s2i-java-pipeline.yaml", "Succeeded"),

		Entry("git-clone task: PIPELINES-XX-TC03",
			"git-clone", "ecosystem/git-clone-pipeline.yaml", "Succeeded"),
	)
})
